/*
 * Team name: GeRMS
 * Team members: Gustavo Moraes, Ryan Ahearn, Mark Morabito, and Samir Leal
 * Date: 04/30/15
 * Purpose: In this project, you and your partners will work to write a program to 
 * create a Math Tutor Software System to help elementary school students.
 *
 * This software will help elementary school students to study and practice math skills.
 *
 * The math curriculum information in Massachusetts is in following link: 
 * http://www.doe.mass.edu/frameworks/math/2000/toc.html
 *
 * The client requests following features as minimum:
 *     practice test materials
 *     tutorials
 *     printing the record(test results)
 *     different level tests for each grade
 *     security(log-in, log-out)
 *     Reward
 *
 */
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.*;
/**
 * This is the Grades 1 and 2 class which stores all of the information including videos, practice, and assessment
 * 
 */
public class Grades1and2 extends JInternalFrame {
    
    // The main class
    private Main main;
    
    // Page count
    private int page = 1;
    
    // ImageIcons for the images of the standards
    private ImageIcon standardIcon1 = new ImageIcon();
 
    /**
     * Creates new form Grades1and2
     */
    public Grades1and2(Main m) {
        // Initializes the components
        initComponents();
        
        // Stores the reference to the main class
        main = m;
        
        // Gets the dimension of the main desktop pane
        Dimension desktopSize = main.getDesktopPaneDimension();
                
        // Gets the size of this JInternalFrame
        Dimension jInternalFrameSize = this.getSize();
        
        // Centers this JInternalFrame in the DesktopPane
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quizButton = new javax.swing.JButton();
        watchButton1 = new javax.swing.JButton();
        practiceButton1 = new javax.swing.JButton();
        standardLabelImage1 = new javax.swing.JLabel();
        rightarrowButton = new javax.swing.JButton();
        leftarrowButton = new javax.swing.JButton();
        finalButton = new javax.swing.JButton();
        pageLabel = new javax.swing.JLabel();
        helpAudioButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Grades 1-2");
        setToolTipText("Grades 1-2");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        quizButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        quizButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PreKK/Quiz.png"))); // NOI18N
        quizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizButtonActionPerformed(evt);
            }
        });

        watchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PreKK/Watch.png"))); // NOI18N
        watchButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        watchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchButton1ActionPerformed(evt);
            }
        });

        practiceButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PreKK/Practice.png"))); // NOI18N
        practiceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practiceButton1ActionPerformed(evt);
            }
        });

        standardLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grades1and2/ComparingNumbers.jpg"))); // NOI18N

        rightarrowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PreKK/RightArrow.png"))); // NOI18N
        rightarrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightarrowButtonActionPerformed(evt);
            }
        });

        leftarrowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PreKK/LeftArrow.png"))); // NOI18N
        leftarrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftarrowButtonActionPerformed(evt);
            }
        });

        finalButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        finalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PreKK/Final.png"))); // NOI18N
        finalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalButtonActionPerformed(evt);
            }
        });

        pageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        pageLabel.setText("1/1");

        helpAudioButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AudioButton.png"))); // NOI18N
        helpAudioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpAudioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(pageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(quizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightarrowButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(finalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(leftarrowButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(standardLabelImage1)
                                .addGap(46, 46, 46)
                                .addComponent(watchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(practiceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpAudioButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(helpAudioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(practiceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(watchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standardLabelImage1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightarrowButton)
                            .addComponent(leftarrowButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pageLabel)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalButton)
                    .addComponent(quizButton))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This method is triggered when the OK button is clicked
    private void quizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizButtonActionPerformed
         
        //Verifies that the user has completed the practice before being allowed to complete a quiz
        String message = "Please complete practice ";
        boolean missingStandard = false;
        String user = main.getUsername();
        dbClass db = new dbClass();
        int[] standards = new int[0];
        String[] standardstext = new String[] {"Comparing numbers "};
        
        standards = db.allpracticescompleted12(user);
        
        for(int i = 0;i<standards.length; i++){
            if (standards[i] == 0){
                message = message.concat(standardstext[i]);
                missingStandard = true;
            }
        }
        message = message.concat("before taking a quiz!");
        
        if (missingStandard){
            JOptionPane.showMessageDialog(null, message, "Complete Standard", JOptionPane.INFORMATION_MESSAGE);
        }else{
            // Closes the Grade 1 and 2 screen
            this.dispose();
            main.setIsGrades1and2ModuleOpen(false);


            // Opens Difficulty Select
            main.openQuizDifficultySelectGrade2();
        }
         
    }//GEN-LAST:event_quizButtonActionPerformed

    // Called when the final button is clicked
    private void finalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalButtonActionPerformed
        String user = main.getUsername();
        dbClass db = new dbClass();
        boolean completed = db.completedhardquiz(user, 2);
        
        if(!completed){
            // Display a message
            JOptionPane.showMessageDialog(null, "Please complete a hard quiz before taking a final test!", "Complete hard!", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            // Opens an assessment at the hard difficulty
            main.openAssessmentScreenGrade2(10, 3);

            // Closes this screen
            main.closeGrades1and2Screen();
        }
        
    }//GEN-LAST:event_finalButtonActionPerformed

    private void practiceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practiceButton1ActionPerformed
        // TODO add your handling code here:

        // Closes the PreK-K module
        this.dispose();

        // Sets the variable to closed
        main.setIsPreKKOpen(false);
        
        // If the current page is 1
        if (page == 1) {
            
            // Opens the KN1 module
            main.openG2N4Screen();
            
        }
        
    }//GEN-LAST:event_practiceButton1ActionPerformed

    private void leftarrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftarrowButtonActionPerformed
        // TODO add your handling code here:

        // If the current page is less than 4
        if (page > 1) {

            // Increments the current page number
            page--;

            // Changes the images displayed on the page
            changePage();

            // Else if the current page is 1
        } else {

            // Display a message
            JOptionPane.showMessageDialog(null, "You're on the first page.", "First Page", JOptionPane.INFORMATION_MESSAGE);

        }

        // Sets the pageLabel text
        pageLabel.setText(page+"/1");

    }//GEN-LAST:event_leftarrowButtonActionPerformed

    private void rightarrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightarrowButtonActionPerformed
        // TODO add your handling code here:

        // If the current page is less than 4
        if (page < 1) {

            // Increments the current page number
            page++;

            // Changes the images on the page
            changePage();

            // Else if the current page is 4
        } else {

            // Display a message
            JOptionPane.showMessageDialog(null, "You're on the last page.", "Last Page", JOptionPane.INFORMATION_MESSAGE);

        }

        // Sets the pageLabel text
        pageLabel.setText(page+"/1");

    }//GEN-LAST:event_rightarrowButtonActionPerformed

    // This method is called when the form is closed
    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
        // This variable is set to false to let us know that this module is closed
        main.setIsGrades1and2ModuleOpen(false);
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void watchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchButton1ActionPerformed
           String videoName = "2N4";
       
            try {
                
                //Creates a file, initialized to null
                File f = null;
            try {
                //Gets the class and resource path of the mp4 video
                f = new File(getClass().getResource("/Videos/" + videoName + " Final.mp4").toURI());
            } catch (URISyntaxException ex) {
                Logger.getLogger(PreKK.class.getName()).log(Level.SEVERE, null, ex);
            }
               //Opens and plays the video with the corresponding video application
                Desktop.getDesktop().open(f);
                
            } catch (IOException ex) {
                Logger.getLogger(PreKK.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_watchButton1ActionPerformed

    private void helpAudioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpAudioButton1ActionPerformed
         /*
        * This is the code to play the audio tutorial .wav file.
        */

        // Creates a File object that is linked the GeRMSLogin.wav filepath
        File yourFile = new File("src/Sounds/Grades1and2.wav");

        AudioInputStream stream;
        AudioFormat format;
        DataLine.Info info;
        Clip clip;

        // A try/catch block to play the .wav file
        try {
            stream = AudioSystem.getAudioInputStream(yourFile);
            format = stream.getFormat();
            info = new DataLine.Info(Clip.class, format);
            clip = (Clip) AudioSystem.getLine(info);
            clip.open(stream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_helpAudioButton1ActionPerformed

    private void changePage() {
        
            // If the current page is now 1
            if (page == 1) {

               // Sets the path for the ImageIcons
               standardIcon1 = new ImageIcon(getClass().getResource("/Images/Grades1and2/CompareNumbers.jpg"));
            
            }
            
            // Changes the images displayed
            standardLabelImage1.setIcon(standardIcon1);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finalButton;
    private javax.swing.JButton helpAudioButton1;
    private javax.swing.JButton leftarrowButton;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JButton practiceButton1;
    private javax.swing.JButton quizButton;
    private javax.swing.JButton rightarrowButton;
    private javax.swing.JLabel standardLabelImage1;
    private javax.swing.JButton watchButton1;
    // End of variables declaration//GEN-END:variables
}
